[package]
name = "grpc"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.48.0", features = ["macros", "rt-multi-thread", "signal"] }
anyhow = "1.0.100"
borsh = "1.5.7"
borsh-derive = "1.5.7"
solana-sdk = "3.0.0"
base64 = "0.22.1"
dotenvy = "0.15.7"
log = "0.4.28"
pretty_env_logger = "0.5.0"
yellowstone-grpc-client = "10.1.1"
yellowstone-grpc-proto = "10.1.1"
futures-util = "0.3.31"
tokio-stream = "0.1.17"
tonic = "0.14.2"
rustls = { version = "0.23.27", features = ["ring"] }

